name: CD Pipeline

on:
   workflow_run:
    workflows: ["CI Pipeline"]
    types: 
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull the Docker Image
      run: sudo docker pull sefaonder101/pipeline:latest
    - name : Delete the old Docker Container
      run: sudo docker rm -f pipeline-container || true
    - name : Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name pipeline-container sefaonder101/pipeline
      
